version: '3.8'

services:
  nexus-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nexus-dev-agent
    restart: unless-stopped
    environment:
      - NEXUS_AGENT_ENV=production
      - NEXUS_LOG_LEVEL=INFO
    volumes:
      - ./config:/app/config:ro
      - nexus_data:/data
      - nexus_logs:/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - nexus-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "nexus-agent", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: nexus-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - nexus-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: nexus-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - nexus-network
    depends_on:
      - prometheus

volumes:
  nexus_data:
  nexus_logs:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  nexus-network:
    driver: bridge