name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety semgrep
    
    - name: Run Bandit security scan
      run: bandit -r src/ -f json -o bandit-results.json
      continue-on-error: true
    
    - name: Run Safety check
      run: safety check --json --output safety-results.json
      continue-on-error: true
    
    - name: Run Semgrep scan
      run: semgrep --config=auto src/
      continue-on-error: true
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-results
        path: |
          bandit-results.json
          safety-results.json